M48
; DRILL file {KiCad 8.0.7-8.0.7-0~ubuntu22.04.1} date 2025-01-08T19:05:11+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-08T19:05:11+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-8.0.7-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X104.977Y-90.057
X107.326Y-89.202
M30
